import { ServiceType } from "@prisma/client";

export const serviceTypeLabel: Record<ServiceType, string> = {
  LA_PATTE: "La Patte",
  LEMPREINTE: "L'Empreinte",
  SITE_ONE_PAGE: "Site One Page",
  SITE_VITRINE: "Site Vitrine",
  KIT_RS: "Kit RS",
  GRAPHISME_A_LA_CARTE: "Graphisme à la carte",
  ACCOMPAGNEMENT_MENSUEL: "Accompagnement mensuel",
  ECOLES_JURY: "Écoles & Jury",
};

export const serviceTypeOptions: { value: ServiceType; label: string }[] = (
  Object.keys(serviceTypeLabel) as ServiceType[]
).map((value) => ({ value, label: serviceTypeLabel[value] }));

/**
 * Étapes du process par type de prestation, utilisées sur la fiche projet (Phase 2).
 */
export const projectSteps: Record<ServiceType, string[]> = {
  LA_PATTE: [
    "Appel découverte",
    "Devis envoyé",
    "Acompte reçu",
    "Questionnaire envoyé",
    "Propositions DA",
    "DA validée",
    "Propositions concepts",
    "Révision(s)",
    "À facturer",
    "Facture envoyée",
    "Solde reçu",
    "Demande avis",
    "Terminé",
  ],
  LEMPREINTE: [
    "Appel découverte",
    "Devis envoyé",
    "Acompte reçu",
    "Questionnaire envoyé",
    "Propositions DA",
    "DA validée",
    "Propositions concepts",
    "Révision(s)",
    "À facturer",
    "Facture envoyée",
    "Solde reçu",
    "Demande avis",
    "Terminé",
  ],
  SITE_ONE_PAGE: [
    "Appel découverte",
    "Devis envoyé",
    "Acompte reçu",
    "Questionnaire envoyé",
    "Contenus reçus",
    "Proposition maquette",
    "Révision(s)",
    "Maquette validée",
    "Intégration",
    "Formation",
    "Mise en ligne",
    "À facturer",
    "Facture envoyée",
    "Solde reçu",
    "Demande avis",
    "Terminé",
  ],
  SITE_VITRINE: [
    "Appel découverte",
    "Devis envoyé",
    "Acompte reçu",
    "Questionnaire envoyé",
    "Contenus reçus",
    "Proposition maquette",
    "Révision(s)",
    "Maquette validée",
    "Intégration",
    "Formation",
    "Mise en ligne",
    "À facturer",
    "Facture envoyée",
    "Solde reçu",
    "Demande avis",
    "Terminé",
  ],
  KIT_RS: [
    "Appel découverte",
    "Devis envoyé",
    "Acompte reçu",
    "Questionnaire envoyé",
    "Proposition",
    "Révision(s)",
    "Livraison Canva",
    "À facturer",
    "Facture envoyée",
    "Solde reçu",
    "Demande avis",
    "Terminé",
  ],
  GRAPHISME_A_LA_CARTE: [
    "Appel découverte",
    "Devis envoyé",
    "Acompte reçu",
    "En création",
    "Révision(s)",
    "Livraison",
    "À facturer",
    "Facture envoyée",
    "Solde reçu",
    "Demande avis",
    "Terminé",
  ],
  ACCOMPAGNEMENT_MENSUEL: [
    "Appel découverte",
    "Devis envoyé",
    "Acompte reçu",
    "En création",
    "Bilan mensuel",
    "À facturer",
    "Facture envoyée",
    "Solde reçu",
    "Renouvellement ou Fin",
    "Demande avis",
    "Terminé",
  ],
  ECOLES_JURY: ["Confirmé", "En cours", "Terminé", "À facturer", "Facture envoyée", "Payé"],
};
